//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta Asunto.
        /// </summary>
        internal static string btnAltaAsunto {
            get {
                return ResourceManager.GetString("btnAltaAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btnAnular {
            get {
                return ResourceManager.GetString("btnAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga de Datos IA.
        /// </summary>
        internal static string btnCargaDatosIA {
            get {
                return ResourceManager.GetString("btnCargaDatosIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string btnCerrar {
            get {
                return ResourceManager.GetString("btnCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Datos.
        /// </summary>
        internal static string btnEditar {
            get {
                return ResourceManager.GetString("btnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        internal static string btnEnviar {
            get {
                return ResourceManager.GetString("btnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Excel.
        /// </summary>
        internal static string btnExportarExcel {
            get {
                return ResourceManager.GetString("btnExportarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Cambios.
        /// </summary>
        internal static string btnGrabar {
            get {
                return ResourceManager.GetString("btnGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar orden.
        /// </summary>
        internal static string btnGuardarOrden {
            get {
                return ResourceManager.GetString("btnGuardarOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar Lista.
        /// </summary>
        internal static string btnOrdenarTask {
            get {
                return ResourceManager.GetString("btnOrdenarTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta Proyectos.
        /// </summary>
        internal static string btnProyecto {
            get {
                return ResourceManager.GetString("btnProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        internal static string btnRegresar {
            get {
                return ResourceManager.GetString("btnRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONAR TODOS.
        /// </summary>
        internal static string btnSeleccionar {
            get {
                return ResourceManager.GetString("btnSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string btnSiguiente {
            get {
                return ResourceManager.GetString("btnSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        internal static string col_Categoria {
            get {
                return ResourceManager.GetString("col_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        internal static string col_Clave {
            get {
                return ResourceManager.GetString("col_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo del Contacto.
        /// </summary>
        internal static string col_CorreoContacto {
            get {
                return ResourceManager.GetString("col_CorreoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve. Categoría.
        /// </summary>
        internal static string col_CveCategoria {
            get {
                return ResourceManager.GetString("col_CveCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve. Cobertura.
        /// </summary>
        internal static string col_Cve_Cobertura {
            get {
                return ResourceManager.GetString("col_Cve_Cobertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve. Línea Negocio.
        /// </summary>
        internal static string col_Cve_LineaNeg {
            get {
                return ResourceManager.GetString("col_Cve_LineaNeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve. Producto.
        /// </summary>
        internal static string col_Cve_Producto {
            get {
                return ResourceManager.GetString("col_Cve_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cve. Sección.
        /// </summary>
        internal static string col_Cve_Seccion {
            get {
                return ResourceManager.GetString("col_Cve_Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Categoría.
        /// </summary>
        internal static string col_DescCategoria {
            get {
                return ResourceManager.GetString("col_DescCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del documento.
        /// </summary>
        internal static string col_DescDocumento {
            get {
                return ResourceManager.GetString("col_DescDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del cliente.
        /// </summary>
        internal static string col_DescripcionCliente {
            get {
                return ResourceManager.GetString("col_DescripcionCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Tarea a realizar.
        /// </summary>
        internal static string col_DescTarea {
            get {
                return ResourceManager.GetString("col_DescTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Cobertura.
        /// </summary>
        internal static string col_Desc_Cobertura {
            get {
                return ResourceManager.GetString("col_Desc_Cobertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Etapa.
        /// </summary>
        internal static string col_Desc_Etapa {
            get {
                return ResourceManager.GetString("col_Desc_Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Producto.
        /// </summary>
        internal static string col_Desc_Producto {
            get {
                return ResourceManager.GetString("col_Desc_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string col_Desc_Seccion {
            get {
                return ResourceManager.GetString("col_Desc_Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Asignación.
        /// </summary>
        internal static string col_Fecha_Asignacion {
            get {
                return ResourceManager.GetString("col_Fecha_Asignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        internal static string col_IdOrden {
            get {
                return ResourceManager.GetString("col_IdOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        internal static string col_IdSeguros {
            get {
                return ResourceManager.GetString("col_IdSeguros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        internal static string col_IdStatus {
            get {
                return ResourceManager.GetString("col_IdStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medida de tiempo.
        /// </summary>
        internal static string col_MedidaTiempo {
            get {
                return ResourceManager.GetString("col_MedidaTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Actor.
        /// </summary>
        internal static string col_NomActor {
            get {
                return ResourceManager.GetString("col_NomActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Asegurado.
        /// </summary>
        internal static string col_NomAsegurado {
            get {
                return ResourceManager.GetString("col_NomAsegurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Cliente.
        /// </summary>
        internal static string col_NomCliente {
            get {
                return ResourceManager.GetString("col_NomCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Contacto.
        /// </summary>
        internal static string col_NomContacto {
            get {
                return ResourceManager.GetString("col_NomContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Demandado.
        /// </summary>
        internal static string col_NomDemandado {
            get {
                return ResourceManager.GetString("col_NomDemandado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Línea de Negocio.
        /// </summary>
        internal static string col_NomLineaNegocio {
            get {
                return ResourceManager.GetString("col_NomLineaNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Proyecto.
        /// </summary>
        internal static string col_NomProyecto {
            get {
                return ResourceManager.GetString("col_NomProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        internal static string col_NomTarea {
            get {
                return ResourceManager.GetString("col_NomTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Póliza.
        /// </summary>
        internal static string col_NumPoliza {
            get {
                return ResourceManager.GetString("col_NumPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Reporte.
        /// </summary>
        internal static string col_NumReporte {
            get {
                return ResourceManager.GetString("col_NumReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Siniestro.
        /// </summary>
        internal static string col_NumSiniestro {
            get {
                return ResourceManager.GetString("col_NumSiniestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num. Registro CONDUSEF.
        /// </summary>
        internal static string col_Num_Condusef {
            get {
                return ResourceManager.GetString("col_Num_Condusef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plazo.
        /// </summary>
        internal static string col_Plazo {
            get {
                return ResourceManager.GetString("col_Plazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia Siniestro.
        /// </summary>
        internal static string col_Referencia {
            get {
                return ResourceManager.GetString("col_Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia Anterior.
        /// </summary>
        internal static string col_Referencia_Anterior {
            get {
                return ResourceManager.GetString("col_Referencia_Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable Administrativo.
        /// </summary>
        internal static string col_Resp_Administrativo {
            get {
                return ResourceManager.GetString("col_Resp_Administrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable Técnico.
        /// </summary>
        internal static string col_Resp_Tecnico {
            get {
                return ResourceManager.GetString("col_Resp_Tecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañia de Seguros.
        /// </summary>
        internal static string col_Seguro_Cia {
            get {
                return ResourceManager.GetString("col_Seguro_Cia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string col_Telefono {
            get {
                return ResourceManager.GetString("col_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num. Extención.
        /// </summary>
        internal static string col_TelExtencion {
            get {
                return ResourceManager.GetString("col_TelExtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono Celular.
        /// </summary>
        internal static string col_TelMovil {
            get {
                return ResourceManager.GetString("col_TelMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tpo. Documento.
        /// </summary>
        internal static string col_TpoDocumento {
            get {
                return ResourceManager.GetString("col_TpoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tpo. Tarea.
        /// </summary>
        internal static string col_TpoInterno {
            get {
                return ResourceManager.GetString("col_TpoInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Asunto.
        /// </summary>
        internal static string col_Tpo_Asunto {
            get {
                return ResourceManager.GetString("col_Tpo_Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad de Tiempo.
        /// </summary>
        internal static string col_UnidadTiempo {
            get {
                return ResourceManager.GetString("col_UnidadTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- No Hay Carpeta(s) --.
        /// </summary>
        internal static string ddl_NoHayCarpeta {
            get {
                return ResourceManager.GetString("ddl_NoHayCarpeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Seleccionar --.
        /// </summary>
        internal static string ddl_Select {
            get {
                return ResourceManager.GetString("ddl_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Seleccionar Columna --.
        /// </summary>
        internal static string ddl_Select_Col {
            get {
                return ResourceManager.GetString("ddl_Select_Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Clientes.
        /// </summary>
        internal static string hdrConsultaClientes {
            get {
                return ResourceManager.GetString("hdrConsultaClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Coberturas.
        /// </summary>
        internal static string hdrConsultaCoberturas {
            get {
                return ResourceManager.GetString("hdrConsultaCoberturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Contactos.
        /// </summary>
        internal static string hdrConsultaContactos {
            get {
                return ResourceManager.GetString("hdrConsultaContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Documentos.
        /// </summary>
        internal static string hdrConsultaDocumentos {
            get {
                return ResourceManager.GetString("hdrConsultaDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Productos.
        /// </summary>
        internal static string hdrConsultaProductos {
            get {
                return ResourceManager.GetString("hdrConsultaProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Proyectos.
        /// </summary>
        internal static string hdrConsultaProyectos {
            get {
                return ResourceManager.GetString("hdrConsultaProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Responsables.
        /// </summary>
        internal static string hdrConsultaResponsable {
            get {
                return ResourceManager.GetString("hdrConsultaResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Tareas.
        /// </summary>
        internal static string hdrConsultaTareas {
            get {
                return ResourceManager.GetString("hdrConsultaTareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Linea de Negocios.
        /// </summary>
        internal static string hdrLineaNegocios {
            get {
                return ResourceManager.GetString("hdrLineaNegocios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASEGURADOS A LOS QUE APLICA(N) ESTE/OS DOCUMENTO(S).
        /// </summary>
        internal static string hdrTituloAsegurados {
            get {
                return ResourceManager.GetString("hdrTituloAsegurados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BIENES A LOS QUE APLICA(N) ESTE/OS DOCUMENTO(S).
        /// </summary>
        internal static string hdrTituloBienes {
            get {
                return ResourceManager.GetString("hdrTituloBienes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DOCUMENTOS REQUERIDOS POR.
        /// </summary>
        internal static string hdrTituloDocumentos {
            get {
                return ResourceManager.GetString("hdrTituloDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTATUS A LOS QUE APLICA(N) ESTE/OS DOCUMENTO(S).
        /// </summary>
        internal static string hdrTituloEstatus {
            get {
                return ResourceManager.GetString("hdrTituloEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OTROS DETALLES A LOS QUE APLICA(N) ESTE/OS DOCUMENTO(S).
        /// </summary>
        internal static string hdrTituloOtrosDetalles {
            get {
                return ResourceManager.GetString("hdrTituloOtrosDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RIESGOS A LOS QUE APLICA(N) ESTE/OS DOCUMENTO(S).
        /// </summary>
        internal static string hdrTituloRiesgos {
            get {
                return ResourceManager.GetString("hdrTituloRiesgos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Nuevo Protocolo (SLA).
        /// </summary>
        internal static string lblAddNewProtocolo {
            get {
                return ResourceManager.GetString("lblAddNewProtocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALTA DE INSPECCIÓN.
        /// </summary>
        internal static string lblAltaInspeccion {
            get {
                return ResourceManager.GetString("lblAltaInspeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALTA DE PROYECTO.
        /// </summary>
        internal static string lblAltaProyecto {
            get {
                return ResourceManager.GetString("lblAltaProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALTA DE REFERENCIA.
        /// </summary>
        internal static string lblAltaReferencia {
            get {
                return ResourceManager.GetString("lblAltaReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asuntos.
        /// </summary>
        internal static string lblAsuntos {
            get {
                return ResourceManager.GetString("lblAsuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de carpeta.
        /// </summary>
        internal static string lblCarpetas {
            get {
                return ResourceManager.GetString("lblCarpetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorias Por.
        /// </summary>
        internal static string lblCategoriasPor {
            get {
                return ResourceManager.GetString("lblCategoriasPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañia de Seguros.
        /// </summary>
        internal static string lblCiaSeguros {
            get {
                return ResourceManager.GetString("lblCiaSeguros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave de Cliente.
        /// </summary>
        internal static string lblClaveCliente {
            get {
                return ResourceManager.GetString("lblClaveCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Cobertura.
        /// </summary>
        internal static string lblCobertura {
            get {
                return ResourceManager.GetString("lblCobertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación.
        /// </summary>
        internal static string lblCodigoVerificacion {
            get {
                return ResourceManager.GetString("lblCodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columna a buscar.
        /// </summary>
        internal static string lblColumnas {
            get {
                return ResourceManager.GetString("lblColumnas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Categorías.
        /// </summary>
        internal static string lblConsultaCategoria {
            get {
                return ResourceManager.GetString("lblConsultaCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Protocolos (SLA).
        /// </summary>
        internal static string lblConsultaProtocolo {
            get {
                return ResourceManager.GetString("lblConsultaProtocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta General de Referencias.
        /// </summary>
        internal static string lblConsultaRef {
            get {
                return ResourceManager.GetString("lblConsultaRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONSULTAS.
        /// </summary>
        internal static string lblConsultas {
            get {
                return ResourceManager.GetString("lblConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Tareas.
        /// </summary>
        internal static string LblConsultaTareas {
            get {
                return ResourceManager.GetString("LblConsultaTareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblContraseña {
            get {
                return ResourceManager.GetString("lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo del Contacto.
        /// </summary>
        internal static string lblCorreoContacto {
            get {
                return ResourceManager.GetString("lblCorreoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CORRESPONDENCIA.
        /// </summary>
        internal static string lblCorrespondencia {
            get {
                return ResourceManager.GetString("lblCorrespondencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Demandado.
        /// </summary>
        internal static string lblDemandado {
            get {
                return ResourceManager.GetString("lblDemandado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Categoría.
        /// </summary>
        internal static string lblDescCategoria {
            get {
                return ResourceManager.GetString("lblDescCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Mote.
        /// </summary>
        internal static string lblDescMote {
            get {
                return ResourceManager.GetString("lblDescMote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de Producto.
        /// </summary>
        internal static string lblDescProducto {
            get {
                return ResourceManager.GetString("lblDescProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del Proyecto.
        /// </summary>
        internal static string lblDescProyecto {
            get {
                return ResourceManager.GetString("lblDescProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del documento (Corta).
        /// </summary>
        internal static string lblDescripBrev {
            get {
                return ResourceManager.GetString("lblDescripBrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del documento (Larga).
        /// </summary>
        internal static string lblDescripLarga {
            get {
                return ResourceManager.GetString("lblDescripLarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Tarea a realizar.
        /// </summary>
        internal static string lblDescTarea {
            get {
                return ResourceManager.GetString("lblDescTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento Interno.
        /// </summary>
        internal static string lblDocInterno {
            get {
                return ResourceManager.GetString("lblDocInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string lblEliminar {
            get {
                return ResourceManager.GetString("lblEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Ocurrencia.
        /// </summary>
        internal static string lblEstOcurrencia {
            get {
                return ResourceManager.GetString("lblEstOcurrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Asignación.
        /// </summary>
        internal static string lblFechaAsignacion {
            get {
                return ResourceManager.GetString("lblFechaAsignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        internal static string lblFiltros {
            get {
                return ResourceManager.GetString("lblFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de Vigencia.
        /// </summary>
        internal static string lblFinVigencia {
            get {
                return ResourceManager.GetString("lblFinVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerente Responsable.
        /// </summary>
        internal static string lblGerente {
            get {
                return ResourceManager.GetString("lblGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string lblIdioma {
            get {
                return ResourceManager.GetString("lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Vigencia.
        /// </summary>
        internal static string lblIniVigencia {
            get {
                return ResourceManager.GetString("lblIniVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Linea de Negocio.
        /// </summary>
        internal static string lblLineaNegocio {
            get {
                return ResourceManager.GetString("lblLineaNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LINEA DE NEGOCIOS.
        /// </summary>
        internal static string lblLineaNegocios {
            get {
                return ResourceManager.GetString("lblLineaNegocios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medida de tiempo.
        /// </summary>
        internal static string lblMedidaTiempo {
            get {
                return ResourceManager.GetString("lblMedidaTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        internal static string lblMenu {
            get {
                return ResourceManager.GetString("lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido:.
        /// </summary>
        internal static string lblMenuBienvenido {
            get {
                return ResourceManager.GetString("lblMenuBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Actor.
        /// </summary>
        internal static string lblNomActor {
            get {
                return ResourceManager.GetString("lblNomActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Asegurado.
        /// </summary>
        internal static string lblNomAsegurado {
            get {
                return ResourceManager.GetString("lblNomAsegurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Cliente.
        /// </summary>
        internal static string lblNombreCliente {
            get {
                return ResourceManager.GetString("lblNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Cliente.
        /// </summary>
        internal static string lblNomCliente {
            get {
                return ResourceManager.GetString("lblNomCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Contacto.
        /// </summary>
        internal static string lblNomContacto {
            get {
                return ResourceManager.GetString("lblNomContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Proyecto.
        /// </summary>
        internal static string lblNomProyecto {
            get {
                return ResourceManager.GetString("lblNomProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Responsable.
        /// </summary>
        internal static string lblNomResponsable {
            get {
                return ResourceManager.GetString("lblNomResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la Sección.
        /// </summary>
        internal static string lblNomSeccion {
            get {
                return ResourceManager.GetString("lblNomSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la Tarea.
        /// </summary>
        internal static string lblNomTarea {
            get {
                return ResourceManager.GetString("lblNomTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num. Registro CONDUSEF.
        /// </summary>
        internal static string lblNumCondusef {
            get {
                return ResourceManager.GetString("lblNumCondusef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Extencion.
        /// </summary>
        internal static string lblNumExtencion {
            get {
                return ResourceManager.GetString("lblNumExtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Póliza.
        /// </summary>
        internal static string lblNumPoliza {
            get {
                return ResourceManager.GetString("lblNumPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Reporte.
        /// </summary>
        internal static string lblNumReporte {
            get {
                return ResourceManager.GetString("lblNumReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Siniestro (Notificación).
        /// </summary>
        internal static string lblNumSiniestro {
            get {
                return ResourceManager.GetString("lblNumSiniestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OPERACIONES.
        /// </summary>
        internal static string lblOperaciones {
            get {
                return ResourceManager.GetString("lblOperaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plazo.
        /// </summary>
        internal static string lblPlazo {
            get {
                return ResourceManager.GetString("lblPlazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto(s).
        /// </summary>
        internal static string lblProducto {
            get {
                return ResourceManager.GetString("lblProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protocolo (SLA).
        /// </summary>
        internal static string lblProtocolos {
            get {
                return ResourceManager.GetString("lblProtocolos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROVEEDORES.
        /// </summary>
        internal static string lblProveedores {
            get {
                return ResourceManager.GetString("lblProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string lblProyecto {
            get {
                return ResourceManager.GetString("lblProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string lblProyectos {
            get {
                return ResourceManager.GetString("lblProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar General de Referencias.
        /// </summary>
        internal static string lblRef {
            get {
                return ResourceManager.GetString("lblRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable Administrativo.
        /// </summary>
        internal static string lblRespAdministrativo {
            get {
                return ResourceManager.GetString("lblRespAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        internal static string lblResponsable {
            get {
                return ResourceManager.GetString("lblResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable Técnico.
        /// </summary>
        internal static string lblRespTecnico {
            get {
                return ResourceManager.GetString("lblRespTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sección.
        /// </summary>
        internal static string lblSecciones {
            get {
                return ResourceManager.GetString("lblSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        internal static string lblTarea {
            get {
                return ResourceManager.GetString("lblTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea Automática.
        /// </summary>
        internal static string lblTareaAutomatica {
            get {
                return ResourceManager.GetString("lblTareaAutomatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea Interna.
        /// </summary>
        internal static string lblTareaInterna {
            get {
                return ResourceManager.GetString("lblTareaInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Celular.
        /// </summary>
        internal static string lblTelMovil {
            get {
                return ResourceManager.GetString("lblTelMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de espera.
        /// </summary>
        internal static string lblTimeSleep {
            get {
                return ResourceManager.GetString("lblTimeSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Asunto.
        /// </summary>
        internal static string lblTipoAsunto {
            get {
                return ResourceManager.GetString("lblTipoAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string lblTitulo {
            get {
                return ResourceManager.GetString("lblTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Archivos de Trabajo.
        /// </summary>
        internal static string lblTitulo_Agregar_Archivos {
            get {
                return ResourceManager.GetString("lblTitulo_Agregar_Archivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALTA DE NUEVA REFERENCIA.
        /// </summary>
        internal static string lblTitulo_Alta_Asunto {
            get {
                return ResourceManager.GetString("lblTitulo_Alta_Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de Cuaderno.
        /// </summary>
        internal static string lblTitulo_Alta_Cuaderno {
            get {
                return ResourceManager.GetString("lblTitulo_Alta_Cuaderno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALTA DE INSPECCIONES.
        /// </summary>
        internal static string lblTitulo_Alta_Inspecciones {
            get {
                return ResourceManager.GetString("lblTitulo_Alta_Inspecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alta de Proyecto.
        /// </summary>
        internal static string lblTitulo_Alta_Proyecto {
            get {
                return ResourceManager.GetString("lblTitulo_Alta_Proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de Categorías al Proyecto.
        /// </summary>
        internal static string lblTitulo_Categoria_Proyecto {
            get {
                return ResourceManager.GetString("lblTitulo_Categoria_Proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Categorías.
        /// </summary>
        internal static string lblTitulo_Cat_Categorias {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Clientes.
        /// </summary>
        internal static string lblTitulo_Cat_Clientes {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Coberturas.
        /// </summary>
        internal static string lblTitulo_Cat_Coberturas {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Coberturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Contactos.
        /// </summary>
        internal static string lblTitulo_Cat_Contactos {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Contactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Documentos.
        /// </summary>
        internal static string lblTitulo_Cat_Documentos {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo Estatus del Siniestro.
        /// </summary>
        internal static string lblTitulo_Cat_Estatus {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta por Etapas/Protocolos.
        /// </summary>
        internal static string lblTitulo_Cat_Etapas {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Etapas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Línea de Negocio.
        /// </summary>
        internal static string lblTitulo_Cat_Linea_Neg {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Linea_Neg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Productos.
        /// </summary>
        internal static string lblTitulo_Cat_Productos {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Protocolos (SLA).
        /// </summary>
        internal static string lblTitulo_Cat_Protocolos {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Protocolos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Responsables.
        /// </summary>
        internal static string lblTitulo_Cat_Responsables {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Responsables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Secciones.
        /// </summary>
        internal static string lblTitulo_Cat_Secciones {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Secciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de Tareas.
        /// </summary>
        internal static string lblTitulo_Cat_Tareas {
            get {
                return ResourceManager.GetString("lblTitulo_Cat_Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta de Secciones.
        /// </summary>
        internal static string lblTitulo_Consulta_Secciones {
            get {
                return ResourceManager.GetString("lblTitulo_Consulta_Secciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Cuaderno.
        /// </summary>
        internal static string lblTitulo_Generar_Cuaderno {
            get {
                return ResourceManager.GetString("lblTitulo_Generar_Cuaderno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SINIESTROS.
        /// </summary>
        internal static string lblTitulo_Mnu_Dinamico {
            get {
                return ResourceManager.GetString("lblTitulo_Mnu_Dinamico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Asegurado.
        /// </summary>
        internal static string lblTpoAsegurado {
            get {
                return ResourceManager.GetString("lblTpoAsegurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        internal static string msgPanelMensaje {
            get {
                return ResourceManager.GetString("msgPanelMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sesión ha expirado..
        /// </summary>
        internal static string msgSesionExpirada {
            get {
                return ResourceManager.GetString("msgSesionExpirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción de Categoría.
        /// </summary>
        internal static string msg_CapturarDescCategoria {
            get {
                return ResourceManager.GetString("msg_CapturarDescCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar nombre de la sección.
        /// </summary>
        internal static string msg_CapturarNomSeccion {
            get {
                return ResourceManager.GetString("msg_CapturarNomSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Clave del Cliente.
        /// </summary>
        internal static string msg_Capturar_ClaveCliente {
            get {
                return ResourceManager.GetString("msg_Capturar_ClaveCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Correo del Contacto.
        /// </summary>
        internal static string msg_Capturar_CorreoContacto {
            get {
                return ResourceManager.GetString("msg_Capturar_CorreoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción de Cobertura.
        /// </summary>
        internal static string msg_Capturar_DescCobertura {
            get {
                return ResourceManager.GetString("msg_Capturar_DescCobertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción del documento (Corta).
        /// </summary>
        internal static string msg_Capturar_DescDocCorta {
            get {
                return ResourceManager.GetString("msg_Capturar_DescDocCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción del documento (Larga).
        /// </summary>
        internal static string msg_Capturar_DescDocLarga {
            get {
                return ResourceManager.GetString("msg_Capturar_DescDocLarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción del Plazo.
        /// </summary>
        internal static string msg_Capturar_DescPlazo {
            get {
                return ResourceManager.GetString("msg_Capturar_DescPlazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción de Producto.
        /// </summary>
        internal static string msg_Capturar_DescProducto {
            get {
                return ResourceManager.GetString("msg_Capturar_DescProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción del Plazo.
        /// </summary>
        internal static string msg_Capturar_Descripcion_Plazo {
            get {
                return ResourceManager.GetString("msg_Capturar_Descripcion_Plazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción de la Tarea.
        /// </summary>
        internal static string msg_Capturar_Descripcion_Tarea {
            get {
                return ResourceManager.GetString("msg_Capturar_Descripcion_Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Descripción de la Tarea.
        /// </summary>
        internal static string msg_Capturar_DescTarea {
            get {
                return ResourceManager.GetString("msg_Capturar_DescTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Nombre de Linea Negocio.
        /// </summary>
        internal static string msg_Capturar_LineaNegocios {
            get {
                return ResourceManager.GetString("msg_Capturar_LineaNegocios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Nombre del Asegurado.
        /// </summary>
        internal static string msg_Capturar_NomAsegurado {
            get {
                return ResourceManager.GetString("msg_Capturar_NomAsegurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Nombre del Cliente.
        /// </summary>
        internal static string msg_Capturar_NombreCliente {
            get {
                return ResourceManager.GetString("msg_Capturar_NombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Nombre del Contacto.
        /// </summary>
        internal static string msg_Capturar_NomContacto {
            get {
                return ResourceManager.GetString("msg_Capturar_NomContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Nombre del Estatus.
        /// </summary>
        internal static string msg_Capturar_NomEstatus {
            get {
                return ResourceManager.GetString("msg_Capturar_NomEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Nombre del proyecto.
        /// </summary>
        internal static string msg_Capturar_NomProyecto {
            get {
                return ResourceManager.GetString("msg_Capturar_NomProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Número de Póliza.
        /// </summary>
        internal static string msg_Capturar_NumPoliza {
            get {
                return ResourceManager.GetString("msg_Capturar_NumPoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Nombre de Responsable.
        /// </summary>
        internal static string msg_Capturar_Responsable {
            get {
                return ResourceManager.GetString("msg_Capturar_Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar tiempo de espera.
        /// </summary>
        internal static string msg_Capturar_Tiempo_Espera {
            get {
                return ResourceManager.GetString("msg_Capturar_Tiempo_Espera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo categoría, correctamente.
        /// </summary>
        internal static string msg_CategoriaActualizada {
            get {
                return ResourceManager.GetString("msg_CategoriaActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego categoría, correctamente.
        /// </summary>
        internal static string msg_CategoriaAgregada {
            get {
                return ResourceManager.GetString("msg_CategoriaAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino categoría, correctamente.
        /// </summary>
        internal static string msg_CategoriaEliminada {
            get {
                return ResourceManager.GetString("msg_CategoriaEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria, se encuentra relacionada a un Asunto.
        /// </summary>
        internal static string msg_CategoriaRelacionadaAsunto {
            get {
                return ResourceManager.GetString("msg_CategoriaRelacionadaAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo cliente, correctamente.
        /// </summary>
        internal static string msg_Cliente_Actualizado {
            get {
                return ResourceManager.GetString("msg_Cliente_Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego cliente, correctamente.
        /// </summary>
        internal static string msg_Cliente_Agregado {
            get {
                return ResourceManager.GetString("msg_Cliente_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino cliente, correctamente.
        /// </summary>
        internal static string msg_Cliente_Eliminado {
            get {
                return ResourceManager.GetString("msg_Cliente_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo cobertura, correctamente.
        /// </summary>
        internal static string msg_Cobertura_Actualizada {
            get {
                return ResourceManager.GetString("msg_Cobertura_Actualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego cobertura, correctamente.
        /// </summary>
        internal static string msg_Cobertura_Agregado {
            get {
                return ResourceManager.GetString("msg_Cobertura_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino cobertura, correctamente.
        /// </summary>
        internal static string msg_Cobertura_Eliminada {
            get {
                return ResourceManager.GetString("msg_Cobertura_Eliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura, se encuentra relacionada a un Asunto.
        /// </summary>
        internal static string msg_Cobertura_Relacionada {
            get {
                return ResourceManager.GetString("msg_Cobertura_Relacionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la categoria ?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Categoria {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el cliente?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Cliente {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la cobertura ?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Cobertura {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Cobertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el contacto?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Contacto {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el documento?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Documento {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el estatus?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Estatus {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar linea de negocios?.
        /// </summary>
        internal static string msg_Confirmar_Delete_LineaNegocio {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_LineaNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el producto ?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Producto {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar el responsable ?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Responsable {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la sección?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Seccion {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Seccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar la tarea?.
        /// </summary>
        internal static string msg_Confirmar_Delete_Tarea {
            get {
                return ResourceManager.GetString("msg_Confirmar_Delete_Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo contacto, correctamente.
        /// </summary>
        internal static string msg_Contacto_Actualizado {
            get {
                return ResourceManager.GetString("msg_Contacto_Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego contacto, correctamente.
        /// </summary>
        internal static string msg_Contacto_Agregado {
            get {
                return ResourceManager.GetString("msg_Contacto_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino contacto, correctamente.
        /// </summary>
        internal static string msg_Contacto_Eliminado {
            get {
                return ResourceManager.GetString("msg_Contacto_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo documento, correctamente.
        /// </summary>
        internal static string msg_Documento_Actualizado {
            get {
                return ResourceManager.GetString("msg_Documento_Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego documento, correctamente.
        /// </summary>
        internal static string msg_Documento_Agregado {
            get {
                return ResourceManager.GetString("msg_Documento_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino documento, correctamente.
        /// </summary>
        internal static string msg_Documento_Eliminado {
            get {
                return ResourceManager.GetString("msg_Documento_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo estatus, correctamente.
        /// </summary>
        internal static string msg_Estatus_Actualizado {
            get {
                return ResourceManager.GetString("msg_Estatus_Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego estatus, correctamente.
        /// </summary>
        internal static string msg_Estatus_Agregado {
            get {
                return ResourceManager.GetString("msg_Estatus_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino estatus, correctamente.
        /// </summary>
        internal static string msg_Estatus_Eliminado {
            get {
                return ResourceManager.GetString("msg_Estatus_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo Linea de Negocio, correctamente.
        /// </summary>
        internal static string msg_LineaNegocios_Actualizado {
            get {
                return ResourceManager.GetString("msg_LineaNegocios_Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego Linea de Negocio, correctamente.
        /// </summary>
        internal static string msg_LineaNegocios_Agregado {
            get {
                return ResourceManager.GetString("msg_LineaNegocios_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino Linea de Negocio, correctamente.
        /// </summary>
        internal static string msg_LineaNegocios_Eliminado {
            get {
                return ResourceManager.GetString("msg_LineaNegocios_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay resultados..
        /// </summary>
        internal static string msg_NoResults {
            get {
                return ResourceManager.GetString("msg_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo producto, correctamente.
        /// </summary>
        internal static string msg_Producto_Actualizado {
            get {
                return ResourceManager.GetString("msg_Producto_Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego producto, correctamente.
        /// </summary>
        internal static string msg_Producto_Agregado {
            get {
                return ResourceManager.GetString("msg_Producto_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino producto, correctamente.
        /// </summary>
        internal static string msg_Producto_Eliminado {
            get {
                return ResourceManager.GetString("msg_Producto_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto, se encuentra relacionado a un Asunto.
        /// </summary>
        internal static string msg_Producto_Relacionado {
            get {
                return ResourceManager.GetString("msg_Producto_Relacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino protocolo, correctamente.
        /// </summary>
        internal static string msg_Protocolo_Eliminado {
            get {
                return ResourceManager.GetString("msg_Protocolo_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino proyecto, correctamente.
        /// </summary>
        internal static string msg_Proyecto_Eliminado {
            get {
                return ResourceManager.GetString("msg_Proyecto_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Proyecto, ya se encuentra registrado.
        /// </summary>
        internal static string msg_Proyecto_Registrado {
            get {
                return ResourceManager.GetString("msg_Proyecto_Registrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo responsable, correctamente.
        /// </summary>
        internal static string msg_Responsable_Actualizado {
            get {
                return ResourceManager.GetString("msg_Responsable_Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino responsable, correctamente.
        /// </summary>
        internal static string msg_Responsable_Eliminado {
            get {
                return ResourceManager.GetString("msg_Responsable_Eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable, se encuentra relacionado a un Asunto.
        /// </summary>
        internal static string msg_Responsable_Relacionado {
            get {
                return ResourceManager.GetString("msg_Responsable_Relacionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego responsable, correctamente.
        /// </summary>
        internal static string msg_Resposable_Agregado {
            get {
                return ResourceManager.GetString("msg_Resposable_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizó sección correctamente.
        /// </summary>
        internal static string msg_Seccion_Actualizada {
            get {
                return ResourceManager.GetString("msg_Seccion_Actualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agregó sección correctamente.
        /// </summary>
        internal static string msg_Seccion_Agregada {
            get {
                return ResourceManager.GetString("msg_Seccion_Agregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino sección, correctamente.
        /// </summary>
        internal static string msg_Seccion_Eliminada {
            get {
                return ResourceManager.GetString("msg_Seccion_Eliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Categorías Por.
        /// </summary>
        internal static string msg_SeleccionarCategoriasPor {
            get {
                return ResourceManager.GetString("msg_SeleccionarCategoriasPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Aseguradora.
        /// </summary>
        internal static string msg_Seleccionar_Aseguradora {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Aseguradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Categoría.
        /// </summary>
        internal static string msg_Seleccionar_Categoria {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Compañia de Seguros.
        /// </summary>
        internal static string msg_Seleccionar_CiaSeguros {
            get {
                return ResourceManager.GetString("msg_Seleccionar_CiaSeguros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Coberturas Por.
        /// </summary>
        internal static string msg_Seleccionar_CoberturaPor {
            get {
                return ResourceManager.GetString("msg_Seleccionar_CoberturaPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Fecha Fin Vigencia.
        /// </summary>
        internal static string msg_Seleccionar_FecFinVigencia {
            get {
                return ResourceManager.GetString("msg_Seleccionar_FecFinVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Fecha Inicio Vigencia.
        /// </summary>
        internal static string msg_Seleccionar_FecIniVigencia {
            get {
                return ResourceManager.GetString("msg_Seleccionar_FecIniVigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Gerente Responsable.
        /// </summary>
        internal static string msg_Seleccionar_Gerente {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Gerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Nombre del Cliente.
        /// </summary>
        internal static string msg_Seleccionar_NomCliente {
            get {
                return ResourceManager.GetString("msg_Seleccionar_NomCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar un producto.
        /// </summary>
        internal static string msg_Seleccionar_Producto {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Protocolo.
        /// </summary>
        internal static string msg_Seleccionar_Protocolo {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Protocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Protocolo (SLA).
        /// </summary>
        internal static string msg_Seleccionar_Protocolo_SLA {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Protocolo_SLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Proyecto.
        /// </summary>
        internal static string msg_Seleccionar_Proyecto {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Tipo de Responsable.
        /// </summary>
        internal static string msg_Seleccionar_Responsable {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Tipo de carpeta.
        /// </summary>
        internal static string msg_Seleccionar_TipoCarpeta {
            get {
                return ResourceManager.GetString("msg_Seleccionar_TipoCarpeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Tipo de Asunto.
        /// </summary>
        internal static string msg_Seleccionar_Tipo_Asunto {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Tipo_Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Tipo de Asegurado.
        /// </summary>
        internal static string msg_Seleccionar_TpoAsegurado {
            get {
                return ResourceManager.GetString("msg_Seleccionar_TpoAsegurado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Tipo de Asunto.
        /// </summary>
        internal static string msg_Seleccionar_TpoAsunto {
            get {
                return ResourceManager.GetString("msg_Seleccionar_TpoAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Unidad de Tiempo.
        /// </summary>
        internal static string msg_Seleccionar_Unidad_Tiempo {
            get {
                return ResourceManager.GetString("msg_Seleccionar_Unidad_Tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo tarea, correctamente.
        /// </summary>
        internal static string msg_Tarea_Actualizada {
            get {
                return ResourceManager.GetString("msg_Tarea_Actualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizo tarea, correctamente.
        /// </summary>
        internal static string msg_Tarea_Actualizado {
            get {
                return ResourceManager.GetString("msg_Tarea_Actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego tarea, correctamente.
        /// </summary>
        internal static string msg_Tarea_Agregada {
            get {
                return ResourceManager.GetString("msg_Tarea_Agregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se agrego tarea, correctamente.
        /// </summary>
        internal static string msg_Tarea_Agregado {
            get {
                return ResourceManager.GetString("msg_Tarea_Agregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino tarea, correctamente.
        /// </summary>
        internal static string msg_Tarea_Eliminada {
            get {
                return ResourceManager.GetString("msg_Tarea_Eliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se elimino tarea, correctamente.
        /// </summary>
        internal static string msg_Tarea_Eliminado {
            get {
                return ResourceManager.GetString("msg_Tarea_Eliminado", resourceCulture);
            }
        }
    }
}
